# Generated by Django 2.2.3 on 2019-07-06 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('time_opened', models.DateTimeField(verbose_name='time opened')),
                ('isp', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('country_name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('longitude', models.CharField(max_length=200)),
            ],
        ),
    ]
