# Generated by Django 2.2.3 on 2019-07-07 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pixels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requests',
            name='region',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
